### ISSUE TITLE
gradlew command wants to download itself

### ISSUE THREAD

**Issue by shilan** [AdoptOpenJDK/jsplitpkgscan#32]
Hi, I am trying to gradlew clean and build without an IDE, but I keep getting this 
Downloading https://services.gradle.org/distributions/gradle-5.4-all.zip
Though I have gradle 5.4 globally installed. 
Since I am behind proxy it won't let it go and download. So I will get connection error and the build will just stop.
gradle clean build --offline doesn't work neither.
Setting GRADLE_HOME and PATH didn't make it any better.

**Comment by reinhapa** [comment]
@shilan you could either edit your ` ~/.gradle/gradle.properties` file and add the needed proxy settings as:
```
systemProp.http.proxyHost = <host>
systemProp.http.proxyPort = <port>
systemProp.http.nonProxyHosts = localhost|127.0.0.1
systemProp.https.proxyHost = <host>
systemProp.https.proxyPort = <port>
systemProp.https.nonProxyHosts = localhost|127.0.0.1
```
or use the global `gradle` executable instead of calling `gradlew`

**Comment by shilan** [comment]
but running with global gradle, i get this error 
Plugin [id: 'com.github.ben-manes.versions', version: '0.21.0'] was not found in
 any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.ben-manes.v
ersions:com.github.ben-manes.versions.gradle.plugin:0.21.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by reinhapa** [comment]
Hmm, I have to look into this later...
